package com.cserver.shared;

public class ServerSettings {
    public static final String srvPubKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOFrurs9bumiw/Dq2gvs2w+VF5BjfgV3/o091WznL+YDenQNqK04tHz/AcF+A1fzNJibDhrDfvYgQQNjskkOKxtsQbWOUQ4dOErJLRIS6WU5NoXJKVW4BwSTeiBAuiECBpXrnPvoqwyI+HDAtg+kQZbhqelIorlabuEmudLZshlZ541xvxOP6V74d8rLbZlFNCmmFunDdBxIvoll+u3st21rpa8SCwRkpVqBIZop1sO3dwRbIvTV3ICqvuYAIS5CpbmPkEHq11408iyanJIykaqLZzkuE2LWaENtt9bdkOVeZaFJ+gqGolJXeBZgHnklycC7AThH/np7qOuvyrt5TwIDAQAB";

}
