#pragma once

#define SREQ_STATUS_SUCCESS				0

#define SREQ_STATUS_ERROR				0xF0000000
#define SREQ_STATUS_NO_CON				SREQ_STATUS_ERROR+1
#define SREQ_STATUS_NO_MEM				SREQ_STATUS_ERROR+2
#define SREQ_STATUS_BAD_RESPONSE		SREQ_STATUS_ERROR+3
#define SREQ_STATUS_BAD_REQUEST			SREQ_STATUS_ERROR+4

#define SREQ_STATUS_WRITE_IO_FAIL		SREQ_STATUS_ERROR+5
#define SREQ_STATUS_READ_IO_FAIL		SREQ_STATUS_ERROR+6
#define SREQ_STATUS_CLIENT_SHUTDOWN		SREQ_STATUS_ERROR+7
#define SREQ_STATUS_NO_RESPONSE			SREQ_STATUS_ERROR+8

